# vision-transformer-cifar/configs/default.yaml
model:
  image_size: 32
  patch_size: 4
  num_classes: 10
  dim: 256
  depth: 6
  heads: 8
  mlp_dim: 512
  dropout: 0.1
  sd_prob: 0.2

data:
  batch_size: 128
  augment: true
  num_workers: 4

training:
  max_epochs: 200
  precision: 16
  accelerator: gpu
  devices: 1
  gradient_clip_val: 1.0
  lr: 3e-4
  weight_decay: 0.05
  label_smoothing: 0.1

logging:
  project: vision-transformer-cifar
  name: vit-base-experiment
